# Introdução ao NumPy


## Importar bibliotecas

In [9]:
import numpy as np
from numpy import random

In [10]:
import os

In [11]:
pip install rarfile

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
# Exemplo:
ex_array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

print(ex_array)

[ 10  20  30  40  50  60  70  80  90 100]


## Versão do NumPy

In [ ]:
print(np.__version__)

1.22.4


## Dimensões em matrizes

### Criando Matrizes 0D

In [ ]:
ex_array = np.array(100)
print(ex_array)
print(type(ex_array))

100
<class 'numpy.ndarray'>


### Matrizes 1D - unidimensional

In [ ]:
ex_array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print(ex_array)
print(type(ex_array))

[ 10  20  30  40  50  60  70  80  90 100]
<class 'numpy.ndarray'>


### Conversão de tipos nos elementos

In [ ]:
ex_array = np.array([10, 20, 30, 40.5, 50.5, 60.5, 70.5, 80, 90, 100])
print(ex_array)
print(type(ex_array))

[ 10.   20.   30.   40.5  50.5  60.5  70.5  80.   90.  100. ]
<class 'numpy.ndarray'>


In [ ]:
ex_array = np.array([10, 20, 30, 40.5, 50.5, 60.5, 70.5, '80', '90', '100'])
print(ex_array)
print(type(ex_array))

['10' '20' '30' '40.5' '50.5' '60.5' '70.5' '80' '90' '100']
<class 'numpy.ndarray'>


### Matrizes 2D

In [ ]:
ex_array = np.array([
                      [10, 20, 30], 
                      [40, 50, 60]
                      ])

print(ex_array)
print(type(ex_array))


[[10 20 30]
 [40 50 60]]
<class 'numpy.ndarray'>


### Matrizes 3D

In [ ]:
ex_array = np.array([
                      [
                       [10, 20, 30], 
                       [40, 50, 60]
                       ], 
                      [
                       [10, 20, 30], 
                       [40, 50, 60]
                       ]
                      ])

print(ex_array)
print(type(ex_array))

[[[10 20 30]
  [40 50 60]]

 [[10 20 30]
  [40 50 60]]]
<class 'numpy.ndarray'>


### Obtendo a quantidade de dimensões ao Array

In [ ]:
ex_array = np.array(42)
print(ex_array.ndim)

0


In [ ]:
ex_array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print(ex_array.ndim)

1


In [ ]:
ex_array = np.array([
                      [10, 20, 30], 
                      [40, 50, 60]
                      ])

print(ex_array.ndim)

2


In [ ]:
ex_array = np.array([[
                       [10, 20, 30], [40, 50, 60]
                       ], 
                      [
                       [10, 20, 30], [40, 50, 60]
                       ]
                      ])

print(ex_array.ndim)

3


### Matrizes com n-dimensões

In [ ]:
ex_array = np.array([21, 22, 23, 24, 25], ndmin=5)

print(ex_array)

print(ex_array.ndim)

[[[[[21 22 23 24 25]]]]]
5


### Criando arrays vazios ou com valores predefinidos

In [ ]:
ex_array = np.empty((4,))
print(ex_array)
print(ex_array.ndim)

[2.47588232e-316 0.00000000e+000 2.70061816e-316 2.70061816e-316]
1


In [ ]:
ex_array = np.empty((3,3))
print(ex_array)
print(ex_array.ndim)


[[2.3824114e-316 0.0000000e+000 0.0000000e+000]
 [0.0000000e+000 0.0000000e+000 0.0000000e+000]
 [0.0000000e+000 0.0000000e+000 3.9525252e-322]]
2


In [ ]:
ex_array = np.ones((3,3))
print(ex_array)
print(ex_array.ndim)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
2


In [ ]:
ex_array = np.zeros((3,5))
print(ex_array)
print(ex_array.ndim)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
2


In [ ]:
ex_array = np.full((3,3), 10)
print(ex_array)
print(ex_array.ndim)

[[10 10 10]
 [10 10 10]
 [10 10 10]]
2


### Adicionar e remover elementos

*   insert(arr, obj, valores [, eixo])
*   Insira valores ao longo do eixo fornecido antes dos índices fornecidos.


In [ ]:
ex_array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print(ex_array)

new_array = np.insert(ex_array,3,888)
print(new_array)

print(ex_array)

[ 10  20  30  40  50  60  70  80  90 100]
[ 10  20  30 888  40  50  60  70  80  90 100]
[ 10  20  30  40  50  60  70  80  90 100]




*   append(arr, valores [, eixo])




In [ ]:
ex_array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print(ex_array)

new_array = np.append(ex_array,[888,999])
print(new_array)

print(ex_array)

[ 10  20  30  40  50  60  70  80  90 100]
[ 10  20  30  40  50  60  70  80  90 100 888 999]
[ 10  20  30  40  50  60  70  80  90 100]




*   delete(arr, obj [, eixo])



In [ ]:
ex_array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print(ex_array)

new_array = np.delete(ex_array,[3,4,5])
print(new_array)

print(ex_array)

[ 10  20  30  40  50  60  70  80  90 100]
[ 10  20  30  70  80  90 100]
[ 10  20  30  40  50  60  70  80  90 100]




*   unique(ar [, return_index, return_inverse,…])




In [ ]:
ex_array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100,10, 20, 30, 40, 50, 60, 70, 80, 90, 100,10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print(ex_array)

new_array = np.unique(ex_array)
print(new_array)

print(ex_array)

[ 10  20  30  40  50  60  70  80  90 100  10  20  30  40  50  60  70  80
  90 100  10  20  30  40  50  60  70  80  90 100]
[ 10  20  30  40  50  60  70  80  90 100]
[ 10  20  30  40  50  60  70  80  90 100  10  20  30  40  50  60  70  80
  90 100  10  20  30  40  50  60  70  80  90 100]


## Indexação de matriz no NumPy

### Acessando um elemento

In [ ]:
ex_array = np.array([21, 22, 23, 24, 25])

print(ex_array[0])
print(ex_array[-1])
print(ex_array[2])

21
25
23


In [ ]:
ex_array = np.array([
                      [21, 22, 23, 24, 25], 
                      [26, 27, 28, 29, 30]
                      ])

print('O terceiro elemento da segunda dimensão: ', ex_array[1, 2])

O terceiro elemento da segunda dimensão:  28


In [ ]:
ex_array = np.array([
                        [
                          [10, 20, 30], 
                          [40, 50, 60]
                        ], 
                        [
                          [70, 80, 90], 
                          [100, 110, 120]
                        ]
                      ])

print(ex_array[0, 1, 2])
print(ex_array[1, 0, 0])
print(ex_array[0, 0, 1])

# Indexação negativa
print(ex_array[-1, -1, -1])
print(ex_array[-2, -2, -2])

60
70
20
120
20


### Recorte de uma matriz

In [ ]:
ex_array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

print(ex_array[1:5])

[20 30 40 50]


In [ ]:
ex_array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

print(ex_array[3:])

[ 40  50  60  70  80  90 100]


In [ ]:
ex_array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

print(ex_array[:4])

[10 20 30 40]


In [ ]:
ex_array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

print(ex_array[-5:-2])

[60 70 80]


In [ ]:
ex_array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

print(ex_array[-3:])

[ 80  90 100]


In [ ]:
# Usando saltos
ex_array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

print(ex_array[0:9:3])

[10 40 70]


In [ ]:
ex_array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

print(ex_array[2: :2])

[30 50 70 90]


In [ ]:
ex_array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

print(ex_array[ : 4 :2])

[10 30]


### Recorte de uma matriz 2D

In [ ]:
ex_array = np.array([
                      [10, 20, 30, 40, 50], 
                      [60, 70, 80, 90, 100],
                      [160, 170, 180, 190, 1100], 
                      [260, 270, 280, 290, 2100]
                      ])

print(ex_array[0, 1:5])

[20 30 40 50]


In [ ]:
print(ex_array[1 , :4])

[60 70 80 90]


### Acessar uma coluna numa matriz 2D

In [ ]:
ex_array = np.array([
                      [10, 20, 30, 40, 50], 
                      [60, 70, 80, 90, 100],
                      [160, 170, 180, 190, 1100], 
                      [260, 270, 280, 290, 2100]
                      ])

print(ex_array[:, 1])

[ 20  70 170 270]


In [ ]:
print(ex_array[:, 2])

[ 30  80 180 280]


In [ ]:
print(ex_array[:, 0:2])

[[ 10  20]
 [ 60  70]
 [160 170]
 [260 270]]


## Tipologia de Dados - NumPy

Tipos de dados em NumPy e os caracteres usados ​​para representá-los.
* i - integer
* b - boolean
* u - unsigned integer
* f - float
* c - complex float
* m - timedelta
* M - datetime
* O - object
* S - string
* U - unicode string

### Checar o tipo de dados de uma matriz

In [ ]:
ex_arraype)

int64


In [ ]:
ex_array = np.array(['José', 'Maria', 'João', 'Zé'])

print(ex_array.dtype)
print(ex_array)

<U5
['José' 'Maria' 'João' 'Zé']


### Definindo o tipo de dado na criação das matrizes

In [ ]:
ex_array = np.array([21, 22, 23, 24, 25], dtype=str)

print(ex_array)
print(ex_array.dtype)

['21' '22' '23' '24' '25']
<U2


In [ ]:
ex_array = np.array([21, 22, 23, 24, 25, 2323423423], dtype='S3')

print(ex_array)
print(ex_array.dtype)

[b'21' b'22' b'23' b'24' b'25' b'232']
|S3


In [ ]:
ex_array = np.array([21, 22, 23, 24, 12312312323234], dtype='i8')

print(ex_array)

print(ex_array.dtype)

[            21             22             23             24
 12312312323234]
int64


### Conversão de tipo de dados em matrizes

* Utilize o método astype() para criar uma cópia da matriz convertida para o novo tipo de dado.
* Como argumento podem ser passadas tanto as letras dos tipos quanto o nomes dos tipos do python.

In [ ]:
ex_array = np.array([1.1, 2.1, 3.1])

novo_array = ex_array.astype('i')

print(novo_array)
print(novo_array.dtype)

[1 2 3]
int32


In [ ]:
novo_array = ex_array.astype('U')

print(novo_array)
print(novo_array.dtype)

['1.1' '2.1' '3.1']
<U32


In [ ]:
ex_array = np.array([
                      [1.1, 2.1, 3.1],
                      [4.1, 5.1, 6.1]
                      ])

novo_array = ex_array.astype('i8')

print(novo_array)
print(novo_array.dtype)

[[1 2 3]
 [4 5 6]]
int64


In [ ]:
# Usando boolean
ex_array = np.array([1, 0, 3])
novo_array = ex_array.astype(bool)

print(novo_array)
print(novo_array.dtype)

[ True False  True]
bool


### NumPy Array copy vs view
* Copy: retorna uma uma nova matriz
* View: apenas uma visualização da matriz original, e as alterações afetarão a matriz original e vice-versa

In [ ]:
ex_array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
copia = ex_array.copy()
copia[0] = 42

print(ex_array)
print(copia)
print(ex_array)

[ 10  20  30  40  50  60  70  80  90 100]
[ 42  20  30  40  50  60  70  80  90 100]
[ 10  20  30  40  50  60  70  80  90 100]


In [ ]:
ex_array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print(ex_array)
visao = ex_array
visao[0] = 250


print(visao)
print(ex_array)

[ 10  20  30  40  50  60  70  80  90 100]
[250  20  30  40  50  60  70  80  90 100]
[250  20  30  40  50  60  70  80  90 100]


## Forma e Remodelagem de Matrizes (shape)

## Forma de matriz NumPy

* Referese ao número de elementos em cada dimensão.
* Use o atributo shape para retornar a tupla com as informações da forma.

In [ ]:
ex_array = np.array([
                      [21, 22, 23, 24], 
                      [25, 26, 27, 28]
                      ])

print(ex_array.shape)
print(f'Essa matriz possuir {ex_array.shape[0]} dimensões com {ex_array.shape[1]} elementos')

(2, 4)
Essa matriz possuir 2 dimensões com 4 elementos


In [ ]:
ex_array = np.array([21, 22, 23, 24, 25], ndmin=4)

print(ex_array)
print('A forma desse array é :', ex_array.shape)

[[[[21 22 23 24 25]]]]
A forma desse array é : (1, 1, 1, 5)


In [ ]:
ex_array = np.array([[
                       [[21, 22, 23, 24, 25],
                        [21, 22, 23, 24, 25],
                        [21, 22, 23, 24, 25]
                       ],
                       [
                        [21, 22, 23, 24, 25],
                        [21, 22, 23, 24, 25],
                        [21, 22, 23, 24, 25]
                       ]
                      ],
                      [
                       [[21, 22, 23, 24, 25],
                        [21, 22, 23, 24, 25],
                        [21, 22, 23, 24, 25]
                       ],
                       [
                        [21, 22, 23, 24, 25],
                        [21, 22, 23, 24, 25],
                        [21, 22, 23, 24, 25]
                       ]
                      ],
   
                      ] )

print(ex_array)

print('A forma desse array é :', ex_array.shape)

[[[[21 22 23 24 25]
   [21 22 23 24 25]
   [21 22 23 24 25]]

  [[21 22 23 24 25]
   [21 22 23 24 25]
   [21 22 23 24 25]]]


 [[[21 22 23 24 25]
   [21 22 23 24 25]
   [21 22 23 24 25]]

  [[21 22 23 24 25]
   [21 22 23 24 25]
   [21 22 23 24 25]]]]
A forma desse array é : (2, 2, 3, 5)


## Remodelagem de Array
* Alterar a forma de uma matriz
* Pode se também adicionar ou remover dimensões ou alterar o número de elementos em cada dimensão.

### De 1D para 2D

In [ ]:
ex_array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 8, 9, 100, 110, 120])

novo_array = ex_array.reshape(5, 3)
print(novo_array)

[[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100   8   9]
 [100 110 120]]


De 1D para 3D

In [ ]:
ex_array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 8, 9, 100, 110, 120, 130, 140, 150])

novo_array = ex_array.reshape(2, 3, 3)
print(novo_array)

[[[ 10  20  30]
  [ 40  50  60]
  [ 70  80  90]]

 [[100   8   9]
  [100 110 120]
  [130 140 150]]]


Pode-se remodelar de qualquer forma desde que a quantidade de elementos seja a mesma!

### NumPy calculando o tamanho de uma das dimensões

In [ ]:
ex_array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

novo_array = ex_array.reshape(2, -1)

print(novo_array)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]]


### Achatamento de matrizes
* Pode se usar reshape(-1) converter uma matriz multidimensional em uma matriz 1D.

In [ ]:
ex_array = np.array([[
                      [10, 20, 30], 
                      [40, 50, 60], 
                      [40, 50, 60]
                      ],
                      [
                      [10, 20, 30], 
                      [40, 50, 60], 
                      [40, 50, 60]
                      ]
                     ]
                      )
print(ex_array.shape)
novo_array = ex_array.reshape(-1)

print(novo_array)

(2, 3, 3)
[10 20 30 40 50 60 40 50 60 10 20 30 40 50 60 40 50 60]


### Achatamento usando flatten

In [ ]:
a = np.array([[1,2,3,4,5,6,7,8,9,10],
              [11,12,13,14,15,16,17,18,19,20],
              [21,22,23,24,25,26,27,28,29,30],
              [31,32,33,34,35,36,37,38,39,40]])
a.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40])

In [ ]:
a.flatten('C')

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40])

In [ ]:
a.flatten('F')

array([ 1, 11, 21, 31,  2, 12, 22, 32,  3, 13, 23, 33,  4, 14, 24, 34,  5,
       15, 25, 35,  6, 16, 26, 36,  7, 17, 27, 37,  8, 18, 28, 38,  9, 19,
       29, 39, 10, 20, 30, 40])

## Interação com Arrays e Matrizes
* forloop para iterar por cada elemento de um array;
* loops aninhados para iterar nos elementos de cada.

### Iteração em Array 1D

In [ ]:
ex_array = np.array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40])

for x in ex_array:
  print(x, end=', ')

1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 

### Iteração em Array 2D

In [ ]:
ex_array = np.array([[1,2,3,4,5,6,7,8,9,10],
              [11,12,13,14,15,16,17,18,19,20],
              [21,22,23,24,25,26,27,28,29,30],
              [31,32,33,34,35,36,37,38,39,40]])

for x in ex_array:
  print(x)

[ 1  2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19 20]
[21 22 23 24 25 26 27 28 29 30]
[31 32 33 34 35 36 37 38 39 40]


In [ ]:
ex_array = np.array([[1,2,3,4,5,6,7,8,9,10],
              [11,12,13,14,15,16,17,18,19,20],
              [21,22,23,24,25,26,27,28,29,30],
              [31,32,33,34,35,36,37,38,39,40]])

for x in ex_array:
  print('linha:', x)
  for y in x:
    print('coluna: ', y, end='; ')
  print('')

linha: [ 1  2  3  4  5  6  7  8  9 10]
coluna:  1; coluna:  2; coluna:  3; coluna:  4; coluna:  5; coluna:  6; coluna:  7; coluna:  8; coluna:  9; coluna:  10; 
linha: [11 12 13 14 15 16 17 18 19 20]
coluna:  11; coluna:  12; coluna:  13; coluna:  14; coluna:  15; coluna:  16; coluna:  17; coluna:  18; coluna:  19; coluna:  20; 
linha: [21 22 23 24 25 26 27 28 29 30]
coluna:  21; coluna:  22; coluna:  23; coluna:  24; coluna:  25; coluna:  26; coluna:  27; coluna:  28; coluna:  29; coluna:  30; 
linha: [31 32 33 34 35 36 37 38 39 40]
coluna:  31; coluna:  32; coluna:  33; coluna:  34; coluna:  35; coluna:  36; coluna:  37; coluna:  38; coluna:  39; coluna:  40; 


In [ ]:
quantidade  = np.array( [1,2,3,4,5,6])
preco = np.array( [10,20,30,40,50,60])

faturamento = quantidade * preco
print(faturamento)

[ 10  40  90 160 250 360]


### Iteração em Matrizes 3D

In [ ]:
ex_array = np.array([
                      [
                       [10, 20, 30], 
                       [40, 50, 60]
                       ], 
                      [
                       [70, 80, 90], 
                       [100, 110, 120]
                       ]
                      ])

for x in ex_array:
  for y in x:
    for z in y:
      print(z)
    print('')
  print('')

10
20
30

40
50
60


70
80
90

100
110
120




### Iteração com nditer()

In [ ]:
ex_array = np.array([
                      [
                       [10, 20, 30], 
                       [40, 50, 60]
                       ], 
                      [
                       [70, 80, 90], 
                       [100, 110, 120]
                       ]
                      ])


for x in np.nditer(ex_array):
  print(x, end=', ')

10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 

### Alterar o tipo de dados dos elementos durante a iteração
* Deve-se indicar o tipo de dado e se será usado um buffer durante a iteração ou se será gerado uma cópia do array.

In [ ]:
ex_array = np.array([10, 20, 30, 40, 50])

for x in np.nditer(ex_array, flags=['buffered'], op_dtypes=['U']):
  print(x)

10
20
30
40
50


In [ ]:
ex_array = np.array([10, 20, 30, 40, 50])

for x in np.nditer(ex_array, flags=['buffered'], op_dtypes=['f8']):
  print(x)

10.0
20.0
30.0
40.0
50.0


## Junção e segmentação de arrays e matrizes


### Junção de Matrizes 1D

In [ ]:
arr1 = np.array([10, 20, 30, 40, 50])

arr2 = np.array([60, 70, 80, 90, 100])

ex_array = np.concatenate((arr1, arr2))
print(ex_array)

[ 10  20  30  40  50  60  70  80  90 100]


### Junção de Matrizes 2D ao longo das linhas (eixo = 1)

In [ ]:
arr1 = np.array([[10, 20], 
                 [30, 40]])

arr2 = np.array([[50, 60], 
                 [70, 80]])

ex_array = np.concatenate((arr1, arr2), axis=1)

print(ex_array)

[[10 20 50 60]
 [30 40 70 80]]


### Junção de Matrizes 2D ao longo das linhas (eixo = 0)

In [ ]:
arr1 = np.array([[10, 20], 
                 [30, 40]])

arr2 = np.array([[50, 60], 
                 [70, 80]])

ex_array = np.concatenate((arr1, arr2), axis=0)

print(ex_array)

[[10 20]
 [30 40]
 [50 60]
 [70 80]]


### Empilhamento de Arrays 1D - np.stack()

In [ ]:
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([60, 70, 80, 90, 100])

ex_array = np.stack((arr1, arr2), axis=0)
print(ex_array)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]]


In [ ]:
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([60, 70, 80, 90, 100])

ex_array = np.stack((arr1, arr2), axis=1)
print(ex_array)

[[ 10  60]
 [ 20  70]
 [ 30  80]
 [ 40  90]
 [ 50 100]]


### Empilhamento de Arrays e Matrizes ao longo das linhas usando hstack()

In [ ]:
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([60, 70, 80, 90, 100])

ex_array = np.hstack((arr1, arr2))
print(ex_array)

[ 10  20  30  40  50  60  70  80  90 100]


In [ ]:
arr1 = np.array([[10, 20], 
                 [30, 40]])

arr2 = np.array([[50, 60], 
                 [70, 80]])

ex_array = np.hstack((arr1, arr2))
print(ex_array)

[[10 20 50 60]
 [30 40 70 80]]


### Empilhamento de Arrays e Matrizes ao longo das colunas usando vstack()

In [ ]:
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([60, 70, 80, 90, 100])

ex_array = np.vstack((arr1, arr2))
print(ex_array)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]]


In [ ]:
arr1 = np.array([[10, 20], 
                 [30, 40]])

arr2 = np.array([[50, 60], 
                 [70, 80]])

ex_array = np.vstack((arr1, arr2))
print(ex_array)

[[10 20]
 [30 40]
 [50 60]
 [70 80]]


### Empilhamento ao longo da altura usanto dstack()


In [ ]:
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([60, 70, 80, 90, 100])

ex_array = np.dstack((arr1, arr2))
print(ex_array)

[[[ 10  60]
  [ 20  70]
  [ 30  80]
  [ 40  90]
  [ 50 100]]]


In [ ]:
arr1 = np.array([[10, 20], 
                 [30, 40]])

arr2 = np.array([[50, 60], 
                 [70, 80]])

ex_array = np.dstack((arr1, arr2))
print(ex_array)

[[[10 50]
  [20 60]]

 [[30 70]
  [40 80]]]


## Quebra e divisão de matrizes e arrays no NumPy
* A função array_split() pode ser usada para dividir matrizes, passamos como argumentos a matriz e o número de divisões.

* Caso o numero de elementos não seja multiplo os ultimos array terão menos elementos, mas não ocorrerá erro na operação.

In [ ]:
ex_array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

novo_array = np.array_split(ex_array, 2)
print(novo_array)

[array([10, 20, 30, 40, 50]), array([ 60,  70,  80,  90, 100])]


In [ ]:
ex_array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

novo_array = np.array_split(ex_array, 3)
print(novo_array)

[array([10, 20, 30, 40]), array([50, 60, 70]), array([ 80,  90, 100])]


In [ ]:
ex_array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

novo_array = np.array_split(ex_array, 4)
print(novo_array)

[array([10, 20, 30]), array([40, 50, 60]), array([70, 80]), array([ 90, 100])]


In [ ]:
ex_array = np.array([
                      [10, 20], 
                      [30, 40],
                      [50, 60], 
                      [70, 80],
                      [90, 100],
                      [110, 120]
                 ])
novo_array = np.array_split(ex_array, 2)

print(novo_array)

[array([[10, 20],
       [30, 40],
       [50, 60]]), array([[ 70,  80],
       [ 90, 100],
       [110, 120]])]


In [ ]:
ex_array = np.array([
                      [10, 20], 
                      [30, 40],
                      [50, 60], 
                      [70, 80],
                      [90, 100],
                      [110, 120]
                 ])

novo_array = np.array_split(ex_array, 3)

print(novo_array)

[array([[10, 20],
       [30, 40]]), array([[50, 60],
       [70, 80]]), array([[ 90, 100],
       [110, 120]])]


In [ ]:
ex_array = np.array([
                      [10, 20], 
                      [30, 40],
                      [50, 60], 
                      [70, 80],
                      [90, 100],
                      [110, 120]
                 ])

novo_array = np.array_split(ex_array, 4)

print(novo_array)

[array([[10, 20],
       [30, 40]]), array([[50, 60],
       [70, 80]]), array([[ 90, 100]]), array([[110, 120]])]


### Função split()
* Esse método é similar ao array_split(), mas falha se a quantidad de elementos não for multiplo da quantidade de divisões.

In [ ]:
ex_array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

novo_array = np.split(ex_array, 2)
print(novo_array)

[array([10, 20, 30, 40, 50]), array([ 60,  70,  80,  90, 100])]


In [ ]:
ex_array = np.array([
                      [10, 20], 
                      [30, 40],
                      [50, 60], 
                      [70, 80],
                      [90, 100],
                      [110, 120]
                 ])

novo_array = np.split(ex_array, 3)

print(novo_array)

[array([[10, 20],
       [30, 40]]), array([[50, 60],
       [70, 80]]), array([[ 90, 100],
       [110, 120]])]


In [ ]:
# casos de erro!
ex_array = np.array([
                      [10, 20], 
                      [30, 40],
                      [50, 60], 
                      [70, 80],
                      [90, 100],
                      [110, 120]
                 ])

novo_array = np.split(ex_array, 4)

print(novo_array)

ValueError: ignored

### Quebrar uma Matriz em arrays de valores das colunas com hsplit()

In [ ]:
ex_array = np.array([[10, 20, 30, 40, 50, 60], 
                      [70, 80, 90, 100, 110, 120], 
                      [130, 140, 150, 160, 170, 180]])

novo_array = np.hsplit(ex_array, 3)
print(novo_array)

[array([[ 10,  20],
       [ 70,  80],
       [130, 140]]), array([[ 30,  40],
       [ 90, 100],
       [150, 160]]), array([[ 50,  60],
       [110, 120],
       [170, 180]])]


### Quebrar uma Matriz em arrays de valores das linhas com vsplit()

In [ ]:
ex_array = np.array([[10, 20, 30], 
                      [40, 50, 60], 
                      [70, 80, 90], 
                      [100, 110, 120], 
                      [130, 140, 150], 
                      [160, 170, 180]])

novo_array = np.vsplit(ex_array, 3)
print(novo_array)

[array([[10, 20, 30],
       [40, 50, 60]]), array([[ 70,  80,  90],
       [100, 110, 120]]), array([[130, 140, 150],
       [160, 170, 180]])]


## Filtros e Ordenação em Arrays e Matrizes

### Pesquisando valores em Arrays usando o método where()

> Exemplo Encontre os índices onde o valor é 3:

In [ ]:
ex_array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

# Encontrar os pares
encontrados_arr = np.where(ex_array % 2 == 0)

print('As posições encontradas foram {}'.format(', '.join([str(p) for p in list(encontrados_arr)])))
print('As valores encontradas foram {}'.format(', '.join([str(ex_array[p]) for p in list(encontrados_arr)])))

As posições encontradas foram [0 1 2 3 4 5 6 7 8 9]
As valores encontradas foram [ 10  20  30  40  50  60  70  80  90 100]


In [ ]:
ex_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Encontrar os impares
encontrados_arr = np.where(ex_array % 2 == 1)

print('As posições encontradas foram {}'.format(', '.join([str(p) for p in list(encontrados_arr)])))
print('As valores encontradas foram {}'.format(', '.join([str(ex_array[p]) for p in list(encontrados_arr)])))

As posições encontradas foram [0 2 4 6 8]
As valores encontradas foram [1 3 5 7 9]


In [ ]:
# Encontrar os multiplos de 3
encontrados_arr = np.where(ex_array % 3 == 0)

print('As posições encontradas foram {}'.format(', '.join([str(p) for p in list(encontrados_arr)])))
print('As valores encontradas foram {}'.format(', '.join([str(ex_array[p]) for p in list(encontrados_arr)])))

As posições encontradas foram [2 5 8]
As valores encontradas foram [30 60 90]


### Inserção em Array ordenado

In [ ]:
ex_array = np.array([1, 2, 3, 4, 5, 6, 8, 9, 10])

# Inserir na 6a posição
x = np.searchsorted(ex_array, 7)
print(x)

6


In [ ]:
ex_array = np.array([1, 3, 5, 7])

# Inserir com uma lista de posições
x = np.searchsorted(ex_array, [2, 4, 6])
print(x)

[1 2 3]


### Ordenação de Matrizes usando sort()
* Colocar os elementos em uma sequência ordenada, numérico ou alfabético, crescente ou decrescente.

In [ ]:
ex_array = np.array([10, 30, 60, 90, 20,100, 70, 80, 40, 50])

print(np.sort(ex_array))

[ 10  20  30  40  50  60  70  80  90 100]


In [ ]:
ex_array = np.array([
                      [10, 30, 60, 90, 20,100, 70, 80, 40, 50],
                      [1, 3, 6, 9, 2,10, 7, 8, 4, 5],
                      [10, 30, 60, 90, 20,100, 70, 80, 40, 50]
])

print(np.sort(ex_array))

[[ 10  20  30  40  50  60  70  80  90 100]
 [  1   2   3   4   5   6   7   8   9  10]
 [ 10  20  30  40  50  60  70  80  90 100]]


In [ ]:
ex_array = np.array(['Norte', 'Sul', 'Leste', 'Oeste'])

print(np.sort(ex_array))

['Leste' 'Norte' 'Oeste' 'Sul']


In [ ]:
ex_array = np.array([True, False, False, False, False, True, True, False, True, False])

print(np.sort(ex_array))

[False False False False False False  True  True  True  True]


### Filtros booleanos

In [ ]:
arr1 = np.array([1,2,3,4,5])
arr1[[False, True, False, True, False]]

array([2, 4])

In [ ]:
ex_array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print(ex_array)

filtro_multip3 = ex_array % 3 == 0
print(filtro_multip3)


array_filtrado = ex_array[filtro_multip3]
print(array_filtrado)

[ 10  20  30  40  50  60  70  80  90 100]
[False False  True False False  True False False  True False]
[30 60 90]


## Geração de valores aleatórios - random

### Import random

In [ ]:
from numpy import random

### Geração de arrays e matrizes com números inteiros

In [ ]:
# Gerando números inteiros
x = random.randint(52)
print(x)

32


In [ ]:
# Gerando matriz de números inteiros aleatórios
x=random.randint(1000, size=(6))
print(x)

[692 100 205 339 388 304]


In [ ]:
x = random.randint(100, size=(3, 5))
print(x)

[[86 59  4 22 60]
 [21 52 32  1 15]
 [73  6 19 24 33]]


### Geração de arrays e matrizes com números reais

In [ ]:
# Gerando números reais
x = random.rand()
print(x)

0.7526882623946036


In [ ]:
x = random.rand(5)
print(x)

[0.0452827  0.04096735 0.00131378 0.17375396 0.98079092]


In [ ]:
x = random.rand(3, 5)
print(x)

[[0.75889413 0.26326467 0.94932172 0.69911798 0.33919535]
 [0.97825743 0.20829188 0.76094134 0.53063847 0.6348308 ]
 [0.24024873 0.15039506 0.21327461 0.07514077 0.81436064]]


### Geração de arrays e matrizes com números reais maiores do que 1

In [ ]:
x=random.randint(100, size=(5)) + random.rand(5) 
print(x)

[88.17432789 12.39162337 75.91612979 18.32982798  8.98898823]


In [ ]:
x=random.randint(80, 220, size=(3, 5)) + random.rand(3, 5) 
print(x)

[[132.61589502 168.50771092 119.59818975 219.16790816 145.65749115]
 [126.51469414 188.16805973 133.29289443 158.56070127 161.63388494]
 [218.51286117 160.72608998 166.26242635 135.75421423  98.08183357]]


### Geração de um número aleatório a partir de uma lista - choice()

In [ ]:
x = random.choice([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print(x)

50


In [ ]:
nomes= [ 'Emanuel', 'Miguel', 'Henry', 'Gael', 'Arthur Henrique', 'Luiz', 
            'José', 'Noah', 'Yago', 'André', 'Felipe', 'Pietro', 'Lucca', 
            'Raul', 'Luiz', 'Fernando', 'Eduardo', 'Ruan', 'Luiz Otávio', 
            'Davi Miguel', 'Rafael', 'Thiago', 'Oliver', 'Rodrigo', 
            'João Gabriel', 'Samuel', 'João Victor', 'Ryan', 'Pedro Miguel', 
            'Bryan', 'Enzo Gabriel', 'Pedro Henrique', 'Augusto', 'Leonardo', 
            'Kauê', 'Davi Lucas', 'Martin', 'Nicolas', 'Bernardo', 
            'Lucas Gabriel', 'Gabriel', 'Miguel Henrique', 'Lorenzo', 'Daniel',
            'Gustavo', 'Caleb', 'Danilo', 'Pedro', 'João Miguel', 'Ian', 
            'Davi', 'Anthony', 'Pedro Lucas', 'Vinícius', 'João', 'Lucas', 
            'Tomás', 'Anthony Gabriel', 'Enzo', 'Bento', 'Benjamin', 'Vicente',
            'Enzo Miguel', 'Théo', 'Fernanda Otávio', 'Matheus', 
            'Levi', 'Benício', 'Victor', 'Joaquim', 'Guilherme', 'Thomas', 
            'Enrico', 'Arthur', 'Carlos', 'Henrique', 'Luiz', 
            'João Guilherme', 'Breno', 'Davi', 'Luiz Henrique', 
            'Murilo', 'Cauã', 'Nathan', 'João Pedro', 'Yuri', 'Victor Hugo', 
            'Antônio', 'Kaique', 'Arthur Miguel', 'João Lucas', 'Caio', 
            'Davi Lucca', 'Arthur', 'Bruno', 'Luan', 'Heitor', 'Francisco', 
            'Isaac', ] 

x = random.choice(nomes)
print(x)

Noah


In [ ]:
x = random.choice(nomes, size=(3, 5))
print(x)

[['Caleb' 'Gabriel' 'Benício' 'Murilo' 'Felipe']
 ['Arthur' 'Luiz Henrique' 'Thomas' 'Lucas Gabriel' 'Enrico']
 ['Davi Miguel' 'Davi' 'José' 'Lucca' 'Anthony Gabriel']]


### Permutações aleatórias - shuffle() e permutation()


In [ ]:
# shuffle() altera a disposição dos elementos na própria matriz.
ex_array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print(ex_array)

np.random.shuffle(ex_array)
print(ex_array)

[ 10  20  30  40  50  60  70  80  90 100]
[ 10  90  50  40 100  30  70  20  80  60]


In [ ]:
# permutation() retorna uma matriz reorganizada (e deixa a matriz original inalterada)
ex_array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print(ex_array)

novo_array = np.random.permutation(ex_array)
print(ex_array)
print(novo_array)

[ 10  20  30  40  50  60  70  80  90 100]
[ 10  20  30  40  50  60  70  80  90 100]
[ 20  70  80  30  90 100  60  40  10  50]


## Funções matemáticas e estatísticas em arrays e matrizes
* ufuncs são "Funções Universais" que operam no objeto ndarray por meio de vetorização (operação baseada em vetor em vez de iteracao) no NumPy, que é muito mais rápido do que iterar sobre os elementos.

* fornecem transmissão e métodos adicionais, como reduzir, acumular, entre outros.

* aceitam argumentos adicionais, como: where, dtype e out.

* operação baseada em vetor são mais rápidas porque as CPUs modernas são otimizadas para esse tipo de operações.

In [ ]:
# criando dois arrays grandes
x = np.random.randint(100, size=(10**7))
y = np.random.randint(100, size=(10**7))
z = []
print(x.shape)

(10000000,)


In [ ]:
# usando laço
%%timeit
for i, j in zip(x, y):
  z.append(i + j)

2.68 s ± 541 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
# usando cálculo vetorial
%%timeit
z = np.add(x, y)

57.9 ms ± 14.5 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


### Referências para cálculos - funções prontas
* Cálculos matemáticos: https://numpy.org/doc/stable/reference/routines.math.html

* Cálculos estatísticos: https://numpy.org/doc/stable/reference/routines.statistics.html

* Calculos financeiros: https://numpy.org/doc/stable/reference/routines.financial.html

* Manipulação de texto: https://numpy.org/doc/stable/reference/routines.char.html

* Algebra linear: https://numpy.org/doc/stable/reference/routines.linalg.html

### Exemplos

In [ ]:
# criando uma matriz
x=random.randint(100, size=(3, 5)) + random.rand(3, 5) 
print(x)

[[76.46847778 65.91710433 65.10177056 23.14489612 67.10225858]
 [57.43407735 97.80020536 98.81761875 48.77623166 92.24952723]
 [58.83099344 72.00681975 52.10860562 94.54878993 66.08777646]]


#### floor(x, /[, out, where, casting, order, …])
* arredondamento para o inteiro menor 

In [ ]:
x=random.randint(100, size=(3, 5)) + random.rand(3, 5) 
print(x)

print()
print(np.floor(x))

print()
print(x)

[[70.63849257 36.90147618 26.41619917 82.60139608 60.00951833]
 [62.80974739 58.32135697 60.00600958 66.40085659  6.08626336]
 [13.60820626 96.2024278  73.72413228 95.74172539  7.20324337]]

[[70. 36. 26. 82. 60.]
 [62. 58. 60. 66.  6.]
 [13. 96. 73. 95.  7.]]

[[70.63849257 36.90147618 26.41619917 82.60139608 60.00951833]
 [62.80974739 58.32135697 60.00600958 66.40085659  6.08626336]
 [13.60820626 96.2024278  73.72413228 95.74172539  7.20324337]]


In [ ]:
x= np.random.randint(100, size=(3, 5)) + np.random.rand(3, 5) 
print(x)

# sobreescreve os vetor inicial
print()
print(np.floor(x, out=x))

print()
print(x)

[[ 4.2181484  30.15024815 63.37466302 78.08427286 77.72386484]
 [15.31197719 35.75833948 55.51627752 74.19087086 85.36181199]
 [10.71706484 23.19175558 84.49884426 86.47840313 70.80144707]]

[[ 4. 30. 63. 78. 77.]
 [15. 35. 55. 74. 85.]
 [10. 23. 84. 86. 70.]]

[[ 4. 30. 63. 78. 77.]
 [15. 35. 55. 74. 85.]
 [10. 23. 84. 86. 70.]]


In [ ]:
x=random.randint(100, size=(3, 5)) + random.rand(3, 5) 
print(x)
print()

resultado = np.zeros(x.shape)
print(np.floor(x, where=x>50 , out=resultado))
print()

print(x)

print()
print(resultado)

[[69.34990506 12.85920997 38.36765478 89.55495549 75.37172524]
 [58.73199359 59.15294902 81.73389907 16.01260045 60.6851137 ]
 [65.80333697 19.78581428  2.38896536 99.81676684 75.27892194]]

[[69.  0.  0. 89. 75.]
 [58. 59. 81.  0. 60.]
 [65.  0.  0. 99. 75.]]

[[69.34990506 12.85920997 38.36765478 89.55495549 75.37172524]
 [58.73199359 59.15294902 81.73389907 16.01260045 60.6851137 ]
 [65.80333697 19.78581428  2.38896536 99.81676684 75.27892194]]

[[69.  0.  0. 89. 75.]
 [58. 59. 81.  0. 60.]
 [65.  0.  0. 99. 75.]]


#### ceil(x, /[, out, where, casting, order, …])
* arredondamento para o inteiro superior

In [ ]:
x=random.randint(100, size=(3, 5)) + random.rand(3, 5) 

print(x)
print(np.ceil(x))

[[19.4591658  67.6090435  33.81953548 22.90267868 29.5312748 ]
 [99.70978601 47.13204026  8.33990701 81.43393729 10.37526541]
 [23.78620242 43.45920013 15.72027905 45.59875731 72.87381124]]
[[ 20.  68.  34.  23.  30.]
 [100.  48.   9.  82.  11.]
 [ 24.  44.  16.  46.  73.]]


#### prod(a[, axis, dtype, out, keepdims, …])
* Retorna o produto dos elementos de um array no eixo informado

In [ ]:
a=random.randint(1,5, size=(3, 2)) 

print(a)
print(np.prod(a,axis=0)) # axis = 0 -> sentido das colunas

[[1 2]
 [4 4]
 [4 3]]
[16 24]


In [ ]:
# Produto das linhas
a=random.randint(1,5, size=(3, 2)) 

print(a)
print(np.prod(a,axis=1)) # axis = 1 -> sentido das linhas

[[2 1]
 [3 3]
 [3 2]]
[2 9 6]


#### sum(a[, axis, dtype, out, keepdims, …])
* Retorna a soma dos elementos do array para o eixo escolhido

In [ ]:
# soma das colunas
a=random.randint(1,5, size=(3, 2)) 

print(a)
print(np.sum(a,axis=0))

[[4 1]
 [1 2]
 [1 4]]
[6 7]


In [ ]:
# soma das linhas
a=random.randint(1,5, size=(3, 2)) 

print(a)
print(np.sum(a,axis=1))

[[2 4]
 [4 2]
 [4 2]]
[6 6 6]


#### exp(x, /[, out, where, casting, order, …])
* Retorna o exponencial dos elementos de um array (e=2.718281)

In [ ]:
a=random.randint(1,5, size=(3, 2)) 

print(a)
print(np.exp(a))

[[3 2]
 [1 4]
 [3 2]]
[[20.08553692  7.3890561 ]
 [ 2.71828183 54.59815003]
 [20.08553692  7.3890561 ]]


#### log10(x, /[, out, where, casting, order, …])
* Retorna o logarítimo na base 10 dos elementos do array

In [ ]:
a=random.randint(1000,2000, size=(3, 2)) 

print(a)
print(np.log10(a))

[[1257 1135]
 [1577 1707]
 [1292 1968]]
[[3.09933528 3.05499586]
 [3.19783169 3.23223352]
 [3.11126251 3.29402509]]


### Estatística
* Cálculos estatísticos: https://numpy.org/doc/stable/reference/routines.statistics.html

#### amin(a[, axis, out, keepdims, initial, where])
* Retorna o menor valor do array para o eixo informado


*   axis=0 sentido das colunas
*   axis=1 sentido das linhas



In [ ]:
a=random.randint(10,70, size=(5, 5)) 

print(a)
print(np.amin(a, axis=0)) # sentido das colunas
print(np.amin(a, axis=1)) # sentido das linhas

[[61 49 47 40 25]
 [53 12 24 27 28]
 [45 49 47 58 10]
 [34 56 56 43 33]
 [46 67 32 20 24]]
[34 12 24 20 10]
[25 12 10 33 20]


#### amax(a[, axis, out, keepdims, initial, where])
* Retorna o maior valor do array para o eixo informado

In [ ]:
a=random.randint(10,70, size=(5, 5)) 

print(a)
print(np.amax(a, axis=0))
print(np.amax(a, axis=1))

[[64 64 35 26 24]
 [10 61 53 29 69]
 [61 51 59 49 18]
 [64 21 42 29 51]
 [51 46 19 36 61]]
[64 64 59 49 69]
[64 69 61 64 61]


#### median(a[, axis, out, overwrite_input, keepdims])
* Retorna a mediana dos valores do array para o eixo informado

In [ ]:
a=random.randint(10,70, size=(5, 5)) 

print(a)
print(np.median(a, axis=0))
print(np.median(a, axis=1))

[[58 64 43 44 60]
 [12 33 51 26 23]
 [58 66 23 66 25]
 [50 59 28 52 14]
 [18 48 55 52 15]]
[50. 59. 43. 52. 23.]
[58. 26. 58. 50. 48.]


#### average(a[, axis, weights, returned])
* Retorna a media ponderada dos valores do array para o eixo informado

In [ ]:
a=random.randint(10,70, size=(5, 5)) 
print(a)

print('media coluna',np.average(a, axis=0))
print('media linha',np.average(a, axis=1))

pesos = random.randint(1,5, size=(5, 5)) 

print('pesos',pesos)
print('media ponderada coluna',np.average(a, axis=0, weights=pesos))
print('media ponderada linha',np.average(a, axis=1, weights=pesos))

[[56 26 43 55 33]
 [45 25 21 59 56]
 [13 68 51 19 69]
 [62 26 49 27 56]
 [62 36 30 45 62]]
media coluna [47.6 36.2 38.8 41.  55.2]
media linha [42.6 41.2 44.  44.  47. ]
pesos [[3 1 3 2 3]
 [3 2 3 4 4]
 [1 2 2 2 1]
 [4 4 1 2 4]
 [3 4 3 2 4]]
media ponderada coluna [53.57142857 35.38461538 36.08333333 44.         54.        ]
media ponderada linha [44.33333333 44.25       44.75       45.26666667 47.375     ]


#### mean(a[, axis, dtype, out, keepdims])
* Retorna a media aritmética dos valores do array para o eixo informado

In [ ]:
a=random.randint(10,70, size=(5, 5)) 

print(a)
print(np.mean(a, axis=0))
print(np.mean(a, axis=1))

[[56 20 16 62 57]
 [49 43 58 53 22]
 [40 35 16 52 20]
 [58 24 14 23 47]
 [39 31 14 27 61]]
[48.4 30.6 23.6 43.4 41.4]
[42.2 45.  32.6 33.2 34.4]


#### std(a[, axis, dtype, out, ddof, keepdims])
* Retorna a desvio-padrao dos valores do array para o eixo informado

In [ ]:
a=random.randint(10,70, size=(5, 5)) 

print(a)
print(np.std(a, axis=0))
print(np.std(a, axis=1))

[[24 61 26 38 19]
 [66 69 63 65 28]
 [55 49 15 43 65]
 [34 36 20 14 17]
 [28 10 11 13 48]]
[16.29232948 20.7557221  18.6868938  19.4792197  18.42389752]
[15.05456741 15.22366579 16.84755175  9.04212364 14.54647724]


#### var(a[, axis, dtype, out, ddof, keepdims])
* Retorna a variância dos valores do array para o eixo informado

In [ ]:
a=random.randint(10,70, size=(5, 5)) 

print(a)
print(np.var(a, axis=0))
print(np.var(a, axis=1))

[[34 40 23 22 17]
 [25 38 32 50 40]
 [33 32 63 12 47]
 [58 36 33 27 62]
 [68 57 11 53 44]]
[270.64  74.24 296.64 257.36 211.6 ]
[ 71.76  69.6  288.24 198.16 376.24]


### Operações Aritméticas entre Arrays e Matrizes

#### Adição
* A função add() soma o conteúdo de duas matrizes e retorna os resultados em uma nova matriz.

In [ ]:
arr1 = np.array([100, 110, 120, 130, 140, 150])
arr2 = np.array([200, 210, 220, 230, 240, 250])

novo_array = np.add(arr1, arr2)

print(novo_array)
print(arr1 + arr2)

[300 320 340 360 380 400]
[300 320 340 360 380 400]


#### Subtração
* A função subtract() subtrai os valores de uma matriz com os valores de outra matriz e retorna os resultados em uma nova matriz.

In [ ]:
arr1 = np.array([100, 110, 120, 130, 140, 150])
arr2 = np.array([200, 210, 220, 230, 240, 250])

novo_array = np.subtract(arr1, arr2)

print(novo_array)
print(arr1 - arr2)

[-100 -100 -100 -100 -100 -100]
[-100 -100 -100 -100 -100 -100]


#### Divisão
A função divide() divide os valores de uma matriz com os valores de outra matriz e retorna os resultados em uma nova matriz.

In [ ]:
arr1 = np.array([100, 110, 120, 130, 140, 150])
arr2 = np.array([200, 210, 220, 230, 240, 250])

novo_array = np.divide(arr2, arr1)

print(novo_array)

[2.         1.90909091 1.83333333 1.76923077 1.71428571 1.66666667]


#### Potenciação
* A função power() eleva os valores da primeira matriz à potência dos valores da segunda matriz e retorna os resultados em uma nova matriz.

In [ ]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([2, 2, 2, 3, 3, 3])

novo_array = np.power(arr1, arr2)
print(novo_array)

[   100    400    900  64000 125000 216000]


#### Resto da Divisão
* As funções mod() e as remainder() retornar o resto da divisão da primeira matriz pela segunda matriz, e devolver os resultados de uma nova matriz.

In [ ]:
# mod
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([2, 5, 4, 6, 7, 9])

novo_array = np.mod(arr1, arr2)
print(novo_array)

[0 0 2 4 1 6]


In [ ]:
# remainder
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([2, 5, 4, 6, 7, 9])

novo_array = np.remainder(arr1, arr2)
print(novo_array)

[0 0 2 4 1 6]


#### Quociente e Resto da Divisão
* A divmod()função retorna o quociente e o mod em dois arrays. O primeiro array contém o quociente e o segundo array contém o resto.

In [ ]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([2, 5, 4, 6, 7, 9])

novo_array = np.divmod(arr1, arr2)
print(novo_array)

(array([5, 4, 7, 6, 7, 6]), array([0, 0, 2, 4, 1, 6]))


#### Valores absolutos
* As funções absolute()e as abs() servem para eliminar o sinal negativo dos valores.

In [ ]:
ex_array = np.array([-10, -34, 11, 32, 34 -65])

novo_array = np.absolute(ex_array)
print(novo_array)

[10 34 11 32 31]


#### Arredondamento de Casas Decimais


##### Truncamento
* Remove os decimais e retorna o número flutuante menor mais próximo de zero

In [ ]:
ex_array = np.trunc([-12.234234, 54.12315])
print(ex_array)

[-12.  54.]


In [ ]:
ex_array = np.fix([-12.234234, 54.12315])
print(ex_array)

[-12.  54.]


##### Arredondamento
* A função around() incrementa o dígito anterior ou decimal em 1 se> = 5, caso contrário, não fará nada.

In [ ]:
ex_array = np.around([-12.57734234, 54.12315], 2)
print(ex_array)

[-12.58  54.12]


In [ ]:
ex_array = np.floor([-12.634234, 54.12315])
print(ex_array)

[-13.  54.]


In [ ]:
ex_array = np.ceil([-12.634234, 54.12315])
print(ex_array)

[-12.  55.]


#### Soma de Matrizes
* Some os valores em arr1 e os valores em arr2:

In [ ]:
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([10, 20, 30, 40, 50])

novo_array = np.sum([arr1, arr2])
print(novo_array)

300


#### Soma sobre determinado eixo
* axis = 0 zero para somar as colunas axis = 1 para somar linhas

In [ ]:
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([10, 20, 30, 40, 50])

novo_array = np.sum([arr1, arr2], axis=1)
print(novo_array)

[150 150]


In [ ]:
arr1 = np.array([10, 20, 30, 40, 50])
arr2 = np.array([10, 20, 30, 40, 50])

novo_array = np.sum([arr1, arr2], axis=0)
print(novo_array)

[ 20  40  60  80 100]


#### Soma Cumulativa
* Soma cumulativa significa adicionar parcialmente os elementos na matriz.

In [ ]:
ex_array = np.array([10, 20, 30, 40, 50])

novo_array = np.cumsum(ex_array)
print(novo_array)

[ 10  30  60 100 150]


#### Produto cumulativo
* Produto cumulativo significa retirar o produto parcialmente.

In [ ]:
ex_array = np.array([1, 2, 3, 4, 5])

novo_array = np.cumprod(ex_array)
print(novo_array)

[  1   2   6  24 120]


#### Diferenças
* Uma diferença discreta significa subtrair dois elementos sucessivos.

In [ ]:
ex_array = np.array([10, 20, 30, 40, 50])
acum_array = np.cumsum(ex_array)

print(acum_array)

dif_array = np.diff(acum_array)
print(dif_array)

[ 10  30  60 100 150]
[20 30 40 50]


#### Operações de conjunto (Coleção de elementos únicos)
* Usa dos para operações de intersecção, união e diferença. O método unique() do NumPy para encontrar elementos exclusivos de qualquer array.

In [ ]:
ex_array = np.array([12, 12, 12, 22, 23, 24, 25, 25, 26, 27])

x = np.unique(ex_array)
print(x)

[12 22 23 24 25 26 27]


#### União

In [ ]:
conj1 = np.array([21, 22, 23, 24, 25])
conj2 = np.array([23, 24, 25, 26])

novo_array = np.union1d(conj1, conj2)
print(novo_array)

[21 22 23 24 25 26]


#### Encontrando intersecção

In [ ]:
conj1 = np.array([21, 22, 23, 24, 25])
conj2 = np.array([23, 24, 25, 26])

novo_array = np.intersect1d(conj1, conj2, assume_unique=True)
print(novo_array)

[23 24 25]


#### Encontrando Diferença
* Use o método setdiff1d() para encontrar apenas os valores no primeiro conjunto que NÃO estão no segundos.

In [ ]:
conj1 = np.array([21, 22, 23, 24, 25])
conj2 = np.array([23, 24, 25, 26])

novo_array = np.setdiff1d(conj1, conj2, assume_unique=True) # setdiff - traz o que é diferente
print(novo_array)

[21 22]


#### Encontrando Diferença Simétrica
* Use o método setxor1d() para encontrar apenas os valores que NÃO estão presentes em AMBOS os conjuntos.

In [ ]:
set1 = np.array([21, 22, 23, 24, 25])
set2 = np.array([23, 24, 25, 26])

novo_array = np.setxor1d(set1, set2, assume_unique=True)
print(novo_array)

[21 22 26]


#### Criar ufunc personalizadas
ufunc: Universal Function

Definir uma função, como você faz com funções normais em Python, e então adicioná-la à sua biblioteca ufunc NumPy com o método frompyfunc().

O métodofrompyfunc() precisa dos seguintes argumentos:

* function: o nome da função.
* inputs: o número de argumentos de entrada - matrizes.
* outputs: o número de matrizes de saída.

In [ ]:
# função que retorna um valor
def adicionar(arr1, arr2):
  return arr1 + arr2

# recebe dois parâmetros e retorna um!
func_adicionar = np.frompyfunc(adicionar, 2, 1)

print(func_adicionar([21, 22, 23, 24], [25, 26, 27, 28]))

[46 48 50 52]


#### Como checar se uma função é um ufunc
* Verifique o tipo de função para verificar se é ufunc ou não.

In [ ]:
print(type(func_adicionar))
print(type(np.add))
print(type(np.add) == np.ufunc)

<class 'numpy.ufunc'>
<class 'numpy.ufunc'>
True


## Numpy - Exportação e Importação de Arrays e Matrizes para Arquivos

### Salvando Arrays em arquivos

In [ ]:
ex_array =random.randint(10,70, size=(5, 5)) 

# fmt: salvando em string
print(ex_array)
np.savetxt("array.csv", ex_array, delimiter=";", fmt='%s')

[[10 14 35 23 32]
 [29 29 65 47 51]
 [18 16 14 58 60]
 [65 49 30 56 44]
 [37 58 63 14 25]]


In [ ]:
with open("array.csv") as f:
  print(f.read())

10;14;35;23;32
29;29;65;47;51
18;16;14;58;60
65;49;30;56;44
37;58;63;14;25



In [ ]:
novo_arr = np.loadtxt('array.csv', delimiter=';', skiprows=0 , dtype=float)
print(novo_arr)

[[10. 14. 35. 23. 32.]
 [29. 29. 65. 47. 51.]
 [18. 16. 14. 58. 60.]
 [65. 49. 30. 56. 44.]
 [37. 58. 63. 14. 25.]]


## Importação de dados externos

### Usando dados do Ministério da Saúde

(https://covid.saude.gov.br/)

### Endereçando os arquivos *.CSV

In [12]:
# criando uma variável para endereço do diretório - esse endereço dependerá de onde você salvará o teu arquivo CSV!
diretorio = os.path.join('/content/drive/MyDrive/Colab Notebooks/[2023 Minor]/[2023 - MIN708]/[2023.03.11] Aula 04 - NumPy/datasets')

### Lendo arquivos *.CSV

In [13]:
nome_arquivo_csv = 'HIST_PAINEL_COVIDBR_2023_Parte1_04mar2023.csv'
caminho_arquivo_csv = os.path.join(diretorio, nome_arquivo_csv)
with open(caminho_arquivo_csv) as f:
  colunas = f.readline().strip('\n').split(';')

In [14]:
# visualizando a primeira linha do dataset
print(colunas)

['regiao', 'estado', 'municipio', 'coduf', 'codmun', 'codRegiaoSaude', 'nomeRegiaoSaude', 'data', 'semanaEpi', 'populacaoTCU2019', 'casosAcumulado', 'casosNovos', 'obitosAcumulado', 'obitosNovos', 'Recuperadosnovos', 'emAcompanhamentoNovos', 'interior/metropolitana']


In [15]:
# comando para ler os primeiros 500 bytes do arquivo
with open(caminho_arquivo_csv) as f:
  print(f.read(500))

regiao;estado;municipio;coduf;codmun;codRegiaoSaude;nomeRegiaoSaude;data;semanaEpi;populacaoTCU2019;casosAcumulado;casosNovos;obitosAcumulado;obitosNovos;Recuperadosnovos;emAcompanhamentoNovos;interior/metropolitana
Brasil;;;76;;;;2023-01-01;1;210147125;36331281;0;693853;0;35006153;631275;
Brasil;;;76;;;;2023-01-02;1;210147125;36362366;31085;693981;128;35081933;586452;
Brasil;;;76;;;;2023-01-03;1;210147125;36390423;28057;694192;211;35147500;548731;
Brasil;;;76;;;;2023-01-04;1;210147125;36423138;


### Usando o NumPy para ler os arquivos

In [16]:
## Carrega os dados no array
dadoscovid = np.loadtxt(caminho_arquivo_csv,
    delimiter=';', skiprows=1 ,     # skiprows ignora a primeira linha para exibir
    dtype='U', encoding='utf-8')    # U = Dados unicode e utf-8 é o tipo de arquivo CSV

## imprime as primeiras linhas do array
print(dadoscovid[:5], '\n')

## imprime as ultimas linhas do 
print(dadoscovid[-5:], '\n')

## verifica a quantidade de dimensões
print(dadoscovid.ndim, '\n')

## verifica a forma do array
print(dadoscovid.shape, '\n')

[['Brasil' '' '' '76' '' '' '' '2023-01-01' '1' '210147125' '36331281'
  '0' '693853' '0' '35006153' '631275' '']
 ['Brasil' '' '' '76' '' '' '' '2023-01-02' '1' '210147125' '36362366'
  '31085' '693981' '128' '35081933' '586452' '']
 ['Brasil' '' '' '76' '' '' '' '2023-01-03' '1' '210147125' '36390423'
  '28057' '694192' '211' '35147500' '548731' '']
 ['Brasil' '' '' '76' '' '' '' '2023-01-04' '1' '210147125' '36423138'
  '32715' '694411' '219' '35196324' '532403' '']
 ['Brasil' '' '' '76' '' '' '' '2023-01-05' '1' '210147125' '36450812'
  '27674' '694569' '158' '35225196' '531047' '']] 

[['Centro-Oeste' 'DF' 'Brasília' '53' '530010' '53001' 'DISTRITO FEDERAL'
  '2023-03-03' '9' '3015268' '897897' '143' '11844' '0' '' '' '1']
 ['Centro-Oeste' 'DF' 'Brasília' '53' '530010' '53001' 'DISTRITO FEDERAL'
  '2023-03-04' '9' '3015268' '0' '-897897' '0' '-11844' '' '' '1']
 ['Centro-Oeste' 'DF' 'Brasília' '53' '530010' '53001' 'DISTRITO FEDERAL'
  '2023-03-05' '10' '3015268' '0' '0' '0' '0' '

### Gerando informações: Brasil

In [17]:
## cria o fitro dos registros estatísticos da covid a nivel Brasil
brasil = dadoscovid[: , 0] == 'Brasil'

## gera array com apenas os dados do brasil
brasilarr = dadoscovid[brasil]

## imprime as primeiras linhas do array
print(brasilarr[:5], '\n')

## imprime as ultimas linhas do 
print(brasilarr[-5:], '\n')

## verifica a quantidade de dimensões
print(brasilarr.ndim, '\n')

## verifica a forma do array
print(brasilarr.shape, '\n')

[['Brasil' '' '' '76' '' '' '' '2023-01-01' '1' '210147125' '36331281'
  '0' '693853' '0' '35006153' '631275' '']
 ['Brasil' '' '' '76' '' '' '' '2023-01-02' '1' '210147125' '36362366'
  '31085' '693981' '128' '35081933' '586452' '']
 ['Brasil' '' '' '76' '' '' '' '2023-01-03' '1' '210147125' '36390423'
  '28057' '694192' '211' '35147500' '548731' '']
 ['Brasil' '' '' '76' '' '' '' '2023-01-04' '1' '210147125' '36423138'
  '32715' '694411' '219' '35196324' '532403' '']
 ['Brasil' '' '' '76' '' '' '' '2023-01-05' '1' '210147125' '36450812'
  '27674' '694569' '158' '35225196' '531047' '']] 

[['Brasil' '' '' '76' '' '' '' '2023-02-28' '9' '210147125' '37052936'
  '14706' '699087' '81' '36235329' '118520' '']
 ['Brasil' '' '' '76' '' '' '' '2023-03-01' '9' '210147125' '37063464'
  '10528' '699197' '110' '36241001' '123266' '']
 ['Brasil' '' '' '76' '' '' '' '2023-03-02' '9' '210147125' '37066791'
  '3327' '699243' '46' '36239891' '127657' '']
 ['Brasil' '' '' '76' '' '' '' '2023-03-03' '9

In [18]:
colunas # listando as colunas

['regiao',
 'estado',
 'municipio',
 'coduf',
 'codmun',
 'codRegiaoSaude',
 'nomeRegiaoSaude',
 'data',
 'semanaEpi',
 'populacaoTCU2019',
 'casosAcumulado',
 'casosNovos',
 'obitosAcumulado',
 'obitosNovos',
 'Recuperadosnovos',
 'emAcompanhamentoNovos',
 'interior/metropolitana']

In [19]:
## verifica se o resultado do filtros gerou o array corretamente - é um teste
# unique: traz apenas os valores unicos da coluna!
print(np.unique(brasilarr[: , 0]))
print(np.unique(brasilarr[: , 1]))
print(np.unique(brasilarr[: , 2]))

['Brasil']
['']
['']


In [20]:
## obtem os índices das colunas que serão utilizadas
colunasselecionadas = ['data',  'casosAcumulado',  'obitosAcumulado']
print(colunasselecionadas, '\n')
print(colunas, '\n')
indice_colunas_selecionadas = [colunas.index(x) for x in colunasselecionadas ]
print(indice_colunas_selecionadas, '\n')

['data', 'casosAcumulado', 'obitosAcumulado'] 

['regiao', 'estado', 'municipio', 'coduf', 'codmun', 'codRegiaoSaude', 'nomeRegiaoSaude', 'data', 'semanaEpi', 'populacaoTCU2019', 'casosAcumulado', 'casosNovos', 'obitosAcumulado', 'obitosNovos', 'Recuperadosnovos', 'emAcompanhamentoNovos', 'interior/metropolitana'] 

[7, 10, 12] 



In [21]:
# formato do brasilarr: são 64 linhas com 17 colunas
brasilarr.shape 

(63, 17)

In [22]:
## remove as colunas desnecessárias do array - só vou trabalhar com 'data', 'casosAcumulado' e 'obtosAcumulado'
brasilarr = brasilarr[: , indice_colunas_selecionadas]

In [23]:
# verficando a dimensão do array: 'data',  'casosAcumulado',  'obitosAcumulado'
brasilarr[0:5] 

array([['2023-01-01', '36331281', '693853'],
       ['2023-01-02', '36362366', '693981'],
       ['2023-01-03', '36390423', '694192'],
       ['2023-01-04', '36423138', '694411'],
       ['2023-01-05', '36450812', '694569']], dtype='<U32')

In [24]:
# formato do brasilarr: são 64 linhas com 3 colunas, ou seja, redimensionado
brasilarr.shape

(63, 3)

In [25]:
# gera a coluna de novos casos a partir dos valores acumulados e adiciona na matriz
# devido a metodologia de registro de novos casos, é necessário calcular esse número a partir de casos acumulados

# calculando pela diferência
novoscasos = np.diff(brasilarr[: , 1].astype('i')).astype(str)

# verificando o resultados
print(brasilarr[: , 1][:10], '\n')      # casos acumulados
print(novoscasos[:10], '\n')            # novos casos a partir da diferença dos acumulados

['36331281' '36362366' '36390423' '36423138' '36450812' '36477214'
 '36488386' '36490050' '36511286' '36552432'] 

['31085' '28057' '32715' '27674' '26402' '11172' '1664' '21236' '41146'
 '26433'] 



In [26]:
# linhas do array brasilarr
brasilarr[: , 1].shape

(63,)

In [27]:
# linhas do array novoscasos
novoscasos.shape

(62,)

In [28]:
# inserindo no array novoscasos o primeiro elemento da diferença = 0
novoscasos =  np.insert(novoscasos,0,0)

In [29]:
#verficando o resultado
print(brasilarr[: , 1][:10], '\n')
print(novoscasos[:10], '\n')

['36331281' '36362366' '36390423' '36423138' '36450812' '36477214'
 '36488386' '36490050' '36511286' '36552432'] 

['0' '31085' '28057' '32715' '27674' '26402' '11172' '1664' '21236'
 '41146'] 



In [30]:
brasilarr.shape

(63, 3)

In [31]:
# linhas do array novoscasos - ajustado ao array brasilarr
novoscasos.shape

(63,)

In [32]:
# reshape novoscasos 
novoscasos = novoscasos.reshape((brasilarr.shape[0],1))

In [33]:
# verificando o array
novoscasos[:5]

array([['0'],
       ['31085'],
       ['28057'],
       ['32715'],
       ['27674']], dtype='<U11')

In [34]:
# concatenando os dois arrays
brasilarr = np.concatenate((brasilarr, novoscasos), axis=1  )

In [35]:
# checando os resultados: 'data', 'casosAcumulado', 'obitosAcumulado', 'novoscasos'
print(brasilarr[0:3], '\n')
print(brasilarr[-3:], '\n')

[['2023-01-01' '36331281' '693853' '0']
 ['2023-01-02' '36362366' '693981' '31085']
 ['2023-01-03' '36390423' '694192' '28057']] 

[['2023-03-02' '37066791' '699243' '3327']
 ['2023-03-03' '37076053' '699276' '9262']
 ['2023-03-04' '37085520' '699310' '9467']] 



In [36]:
# criando a coluna novosobitos - usando a mesma metodologia do exemplo anterior
# gera a coluna de novos obitos a partir dos valores acumulados e adiciona na matriz
# novos obtos pela diferença 
novosobitos = np.diff(brasilarr[: , 2].astype('i')).astype(str)
novosobitos = np.insert(novosobitos,0,0)
novosobitos = novosobitos.reshape((brasilarr.shape[0],1))
brasilarr = np.concatenate((brasilarr, novosobitos), axis=1  )

# exibindo os formatos da tabela final: 'data', 'casosAcumulado', 'obitosAcumulado', 'novoscasos', novosobitos
print(brasilarr[0:3], '\n')
print(brasilarr[-3:], '\n')

[['2023-01-01' '36331281' '693853' '0' '0']
 ['2023-01-02' '36362366' '693981' '31085' '128']
 ['2023-01-03' '36390423' '694192' '28057' '211']] 

[['2023-03-02' '37066791' '699243' '3327' '46']
 ['2023-03-03' '37076053' '699276' '9262' '33']
 ['2023-03-04' '37085520' '699310' '9467' '34']] 



In [37]:
# verificando os novosobitos
693981-693853

128

### Organizar o total de obitos por mês

#### Gerando uma lista com Ano-Mês

In [38]:
# np.unique: apenas os valores únicos
# lambda x: x[:7] - extraindo 7 caracteres
# resultado: apenas a lista dos meses
meses_arr = np.sort(np.unique(np.array(list(map(lambda x : x[:7] , np.unique(brasilarr[:,0]))))))
meses_arr

array(['2023-01', '2023-02', '2023-03'], dtype='<U7')

In [40]:
casos_mes_arr = None
for mes in meses_arr:                                                 # calcular para todos os meses
  filtro =  np.array([mes in x for x in brasilarr[:,0]])              # criando um array de booleanos para usar como filtro!
  casos_arr = brasilarr[filtro,3].astype('i')                         # criando um array e selecionando a coluna 3 - casosnovos
  total_casos = np.sum(casos_arr)                                     # somar e obter a quantidade de casos
  obitos_arr = brasilarr[filtro,4].astype('i')                        # criando um array e selecionando a coluna 3 - obitos
  total_obitos = np.sum(obitos_arr)                                   # somar e obter a quantidade de obitos
  arraytemp = np.array([mes, total_casos, total_obitos], dtype=str)   # criando um array temporário com os valores acumulados
  if casos_mes_arr is None:                                           # inicia a primeira linha do array casos_mes_arr
    casos_mes_arr = arraytemp
  else: 
    casos_mes_arr = np.vstack((casos_mes_arr,arraytemp ))

print(casos_mes_arr)

[['2023-01' '493299' '3221']
 ['2023-02' '228356' '2013']
 ['2023-03' '32584' '223']]


In [41]:
# Calcular novos casos diferença mes a mes
novoscasos = np.diff(casos_mes_arr[: , 1].astype('i')).astype(str)
novoscasos =  np.insert(novoscasos,0,0)
print(novoscasos)

#Adicionar novos casos no array
novoscasos = novoscasos.reshape((casos_mes_arr.shape[0],1))
casos_mes_arr = np.concatenate((casos_mes_arr, novoscasos), axis=1)
print(casos_mes_arr)

['0' '-264943' '-195772']
[['2023-01' '493299' '3221' '0']
 ['2023-02' '228356' '2013' '-264943']
 ['2023-03' '32584' '223' '-195772']]


In [42]:
# Calcular novos obtidos diferença mes a mes
novosobitos = np.diff(casos_mes_arr[: , 2].astype('i')).astype(str)
novosobitos =  np.insert(novosobitos,0,0)
print(novosobitos)

#Adicionar novos casos no array
novosobitos = novosobitos.reshape((casos_mes_arr.shape[0],1))
casos_mes_arr = np.concatenate((casos_mes_arr, novosobitos), axis=1)
print(casos_mes_arr)

['0' '-1208' '-1790']
[['2023-01' '493299' '3221' '0' '0']
 ['2023-02' '228356' '2013' '-264943' '-1208']
 ['2023-03' '32584' '223' '-195772' '-1790']]


In [43]:
# Calcular casos acumulados mes a mes
casosacumulados = np.cumsum(casos_mes_arr[: , 1].astype('i')).astype(str)
print(casosacumulados)

#Adicionar casos acumulados no array
casosacumulados = casosacumulados.reshape((casos_mes_arr.shape[0],1))
casos_mes_arr = np.concatenate((casos_mes_arr, casosacumulados), axis=1)
print(casos_mes_arr)

['493299' '721655' '754239']
[['2023-01' '493299' '3221' '0' '0' '493299']
 ['2023-02' '228356' '2013' '-264943' '-1208' '721655']
 ['2023-03' '32584' '223' '-195772' '-1790' '754239']]


In [44]:
# Calcular obitos acumulados mes a mes
obitosacumulados = np.cumsum(casos_mes_arr[: , 2].astype('i')).astype(str)
print(obitosacumulados)

#Adicionar obitos acumulados no array
obitosacumulados = obitosacumulados.reshape((casos_mes_arr.shape[0],1))
casos_mes_arr = np.concatenate((casos_mes_arr, obitosacumulados), axis=1)
print(casos_mes_arr)

['3221' '5234' '5457']
[['2023-01' '493299' '3221' '0' '0' '493299' '3221']
 ['2023-02' '228356' '2013' '-264943' '-1208' '721655' '5234']
 ['2023-03' '32584' '223' '-195772' '-1790' '754239' '5457']]


In [45]:
print(casos_mes_arr)

[['2023-01' '493299' '3221' '0' '0' '493299' '3221']
 ['2023-02' '228356' '2013' '-264943' '-1208' '721655' '5234']
 ['2023-03' '32584' '223' '-195772' '-1790' '754239' '5457']]


In [46]:
#Reorganizando as colunas
casos_mes_arr = casos_mes_arr[: , [0,1,3,5,2,4,6]]
print(casos_mes_arr)

[['2023-01' '493299' '0' '493299' '3221' '0' '3221']
 ['2023-02' '228356' '-264943' '721655' '2013' '-1208' '5234']
 ['2023-03' '32584' '-195772' '754239' '223' '-1790' '5457']]


In [47]:
# adicionando o nome das colunas
colunas = np.array(['DATA', 'CASOS_NOVOS', 'CASOS_ACUMULADOS',
           'CASOS_DIF_MES_ANT', 
           'OBITOS_NOVOS', 'OBITOS_ACUMULADOS',
           'OBITOS_DIF_MES_ANT'])

colunas.shape     

(7,)

In [48]:
casos_mes_arr= np.vstack((colunas, casos_mes_arr))

In [49]:
casos_mes_arr.shape 

(4, 7)

In [50]:
casos_mes_arr

array([['DATA', 'CASOS_NOVOS', 'CASOS_ACUMULADOS', 'CASOS_DIF_MES_ANT',
        'OBITOS_NOVOS', 'OBITOS_ACUMULADOS', 'OBITOS_DIF_MES_ANT'],
       ['2023-01', '493299', '0', '493299', '3221', '0', '3221'],
       ['2023-02', '228356', '-264943', '721655', '2013', '-1208',
        '5234'],
       ['2023-03', '32584', '-195772', '754239', '223', '-1790', '5457']],
      dtype='<U21')

In [51]:
np.savetxt("casos_mes_arr.csv", casos_mes_arr, delimiter=";", fmt='%s')